[package]
name = "bril-rs"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
dot-generator = "0.2.0"
dot-structures = "0.1.1"
graphviz-rust = "0.9.3"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] } 
serde_json = "1.0.137"
